POST  http://localhost:4000/api/username
Content-Type: application/json

{
          "Name": "Ayush Rai ",
          "Age":45, 
          "Birth":"2003-10-26",
          "Email": "ayush@vitbhopal.ac.in",
          "Password": "456"

}
###


Get http://localhost:4000/api/usernames
Content-Type: application/json

###
DELETE http://localhost:4000/api/usernames
Content-Type: application/json

###
DELETE  http://localhost:4000/api/username/6371f0bdcf6c66938a749177
Content-Type: application/json

